logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
spring:
  application:
    name: helloWorld
  datasource:
    url: jdbc:h2:file:./h2/db
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  batch:
    initialize-schema: always